### ISSUE TITLE
In fact, in survival mode, Middle click has no function, so it is impossible to Edit residence''s icon.

### ISSUE THREAD

**Issue by RICE0707** [ArtformGames/ResidenceList#51]
As the title says,` Middle click `is only valid in creative mode.
It is recommended to change to` SHITF + left click `or` SHITF + right click `.
```
      information:
        material: OAK_SIGN
        name: '&e&lEdit information'
        lore:
        - ''
        - '&a ▶ LClick &8|&f Set residence''s nickname.'
        - '&a ▶ RClick &8|&f Set residence''s description.'
        - '&a ▶ Middle &8|&f Edit residence''s icon'
```
